steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_ID}/${_SERVICE_NAME}:${_IMAGE_TAG}
      - --context=dir://.
      - --dockerfile=./Dockerfile
      - --cache=false
    id: 'Build and Push with Kaniko'

substitutions:
  _REGION: 'us-central1'
  _REPO_ID: 'adk-agent-images'
  _SERVICE_NAME: 'adk-multi-agent-demo'
  _IMAGE_TAG: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'